#!/usr/bin/env python3
"""
Generate package.xml manifests for the sandbox → production path from the ATF template tree,
so the member lists always match what the templates create.

  python3 scripts/build_manifests.py            # writes manifests/manifest_assets.xml, manifest_lwc.xml, manifest_datakit.xml

Asset API names are the ones Tableau Next assigns at creation time (the chain names workspaces,
vizzes and dashboards after the JSON "name"), which is why the templates use fixed names rather
than labels-with-spaces. Semantic models get a numeric suffix (…_Model_988) at creation, so the
data-kit manifest must be re-read from the org: use `sf project retrieve start --metadata DataKit:*`
or the names printed by scripts/verify.sh.
"""
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TPL = os.path.join(ROOT, "force-app", "main", "default", "appTemplates")
OUT = os.path.join(ROOT, "manifests")


def names(sub):
    out = []
    for f in sorted(glob.glob(os.path.join(TPL, "Cumulus_*", sub, "*.json"))):
        with open(f) as fh:
            out.append(json.load(fh).get("name") or os.path.splitext(os.path.basename(f))[0])
    return sorted(set(out))


def package(types, comment=""):
    lines = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>']
    if comment:
        lines.append(f"<!-- {comment} -->")
    lines.append('<Package xmlns="http://soap.sforce.com/2006/04/metadata">')
    for t, members in types:
        lines.append("    <types>")
        lines += [f"        <members>{m}</members>" for m in members]
        lines.append(f"        <name>{t}</name>\n    </types>")
    lines.append("    <version>67.0</version>\n</Package>\n")
    return "\n".join(lines)


def main():
    os.makedirs(OUT, exist_ok=True)
    assets = [("AnalyticsWorkspace", names("workspaces")), ("AnalyticsVisualization", names("visualizations")), ("AnalyticsDashboard", names("dashboards"))]
    with open(os.path.join(OUT, "manifest_assets.xml"), "w") as f:
        f.write(package(assets, "Tableau Next assets for the seven Cumulus workspaces — generated by scripts/build_manifests.py. "
                                "Deploy the data kit first so the semantic models exist in the target org. "
                                "Retrieve: sf project retrieve start --manifest manifests/manifest_assets.xml -o <sandbox>; "
                                "Deploy: sf project deploy start --manifest manifests/manifest_assets.xml -o <prod>"))
    lwcs = sorted(os.path.basename(p) for p in glob.glob(os.path.join(ROOT, "force-app", "main", "default", "lwc", "cumulus*")))
    with open(os.path.join(OUT, "manifest_lwc.xml"), "w") as f:
        f.write(package([("LightningComponentBundle", lwcs)], "Dashboard extension LWCs — deploy BEFORE the dashboards that reference them (c:<component> widgets)."))
    templates = sorted(os.path.basename(p) for p in glob.glob(os.path.join(TPL, "Cumulus_*")))
    with open(os.path.join(OUT, "manifest_templates.xml"), "w") as f:
        f.write(package([("AppFrameworkTemplateBundle", templates)], "App Template Framework bundles — the packaging path (2GP) and the 'install into any org' path."))
    with open(os.path.join(OUT, "manifest_datakit.xml"), "w") as f:
        f.write(package([("DataKit", ["Cumulus_FinServ_Data_Kit"])], "Data 360 data kit (data streams + DLOs + DMOs + semantic models). Create it in Data 360 Setup → Data Kits, "
                                                                  "add the Cumulus semantic models, then retrieve with this manifest and deploy it to production FIRST."))
    print("wrote", ", ".join(sorted(os.listdir(OUT))))
    for t, m in assets:
        print(f"  {t}: {len(m)}")


if __name__ == "__main__":
    main()
