#!/usr/bin/env python3
"""
Load the Cumulus CSVs into Data 360 through the Ingestion API (bulk).

Prerequisites (one-time, in Data 360 Setup):
  1. Connectors → New → Ingestion API → name it  cumulus  → upload data/ingestion/cumulus_schema.yaml
     (one object per CSV table; the schema is generated by data/generate.py).
  2. Data Streams → New → Ingestion API → source "cumulus" → select all objects → creates one DLO per table.
     (In the packaged version these streams ship inside the data kit; you only need step 1's connector.)
  3. An External Client App (or Connected App) with scopes  cdp_ingest_api, api, refresh_token  and a
     user with Data Cloud Architect. Authenticate with the Salesforce CLI and this script reuses the token.

Usage:
  python3 scripts/load_data.py --org buildorg [--source cumulus] [--only rb_service_cases,ins_claims] [--dry-run]

Flow per table: Salesforce access token (sf org display) → Data 360 token exchange (/services/a360/token)
  → POST /api/v1/ingest/jobs {object, sourceName, operation: upsert} → PUT jobs/{id}/batches (CSV, ≤150 MB)
  → PATCH jobs/{id} {state: UploadComplete} → poll until JobComplete.
Docs: https://developer.salesforce.com/docs/data/data-cloud-int/guide/c360-a-api-bulk-ingestion.html
"""
import argparse
import glob
import json
import os
import subprocess
import sys
import time
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "data", "out")


def sf_org(alias):
    j = json.loads(subprocess.check_output(["sf", "org", "display", "-o", alias, "--json"]))["result"]
    return j["accessToken"], j["instanceUrl"]


def http(method, url, data=None, headers=None, ctype="application/json"):
    body = None
    if data is not None:
        body = data if isinstance(data, (bytes, bytearray)) else json.dumps(data).encode()
    req = urllib.request.Request(url, data=body, method=method, headers={"Content-Type": ctype, **(headers or {})})
    try:
        with urllib.request.urlopen(req, timeout=600) as r:
            raw = r.read()
            return r.status, (json.loads(raw) if raw and r.headers.get("Content-Type", "").startswith("application/json") else raw)
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode(errors="replace")


def dc_token(core_token, instance_url):
    """Exchange the core access token for a Data 360 token (urn:salesforce:grant-type:external:cdp)."""
    data = f"grant_type=urn:salesforce:grant-type:external:cdp&subject_token={core_token}&subject_token_type=urn:ietf:params:oauth:token-type:access_token".encode()
    st, j = http("POST", f"{instance_url}/services/a360/token", data, ctype="application/x-www-form-urlencoded")
    if st != 200:
        sys.exit(f"Data 360 token exchange failed ({st}): {j}")
    return j["access_token"], "https://" + j["instance_url"]


def load_table(base, hdr, source, table, csv_path, dry):
    size = os.path.getsize(csv_path)
    print(f"→ {table:40s} {size / 1e6:6.1f} MB", end=" ")
    if dry:
        print("(dry run)")
        return
    st, job = http("POST", f"{base}/api/v1/ingest/jobs", {"object": table, "sourceName": source, "operation": "upsert"}, hdr)
    if st not in (200, 201):
        print(f"\n   create job failed ({st}): {job}")
        return False
    jid = job["id"]
    with open(csv_path, "rb") as f:
        st, r = http("PUT", f"{base}/api/v1/ingest/jobs/{jid}/batches", f.read(), hdr, ctype="text/csv")
    if st not in (200, 201, 202):
        print(f"\n   upload failed ({st}): {r}")
        return False
    http("PATCH", f"{base}/api/v1/ingest/jobs/{jid}", {"state": "UploadComplete"}, hdr)
    for _ in range(120):
        st, j = http("GET", f"{base}/api/v1/ingest/jobs/{jid}", None, hdr)
        state = j.get("state") if isinstance(j, dict) else "?"
        if state in ("JobComplete", "Failed", "Aborted"):
            break
        time.sleep(5)
    print(f"job {jid} → {state}")
    return state == "JobComplete"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--org", required=True, help="Salesforce CLI org alias")
    ap.add_argument("--source", default="cumulus", help="Ingestion API connector (source) name")
    ap.add_argument("--only", help="comma-separated table names")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    files = sorted(glob.glob(os.path.join(OUT, "*", "*.csv")))
    if a.only:
        keep = set(a.only.split(","))
        files = [f for f in files if os.path.splitext(os.path.basename(f))[0] in keep]
    if not files:
        sys.exit("No CSVs found — run python3 data/generate.py first.")
    if a.dry_run:
        base, hdr = "", {}
    else:
        core, inst = sf_org(a.org)
        tok, base = dc_token(core, inst)
        hdr = {"Authorization": f"Bearer {tok}"}
    ok = 0
    for f in files:
        if load_table(base, hdr, a.source, os.path.splitext(os.path.basename(f))[0], f, a.dry_run) is not False:
            ok += 1
    print(f"\n{ok}/{len(files)} tables submitted. Data 360 processes upserts asynchronously — allow a few minutes, then refresh the semantic models in Tableau Next.")


if __name__ == "__main__":
    main()
